### ISSUE TITLE
invalid manifest format

### ISSUE THREAD

**Issue by Klumbumbus** [iandees/josm-mbtiles#13]
There is a problem with the new version 2.2.0. It can't be loaded in the JOSM list an the console prints:

````
2017-03-15 19:07:46.693 SEVERE: org.openstreetmap.josm.plugins.PluginListParseException: Failed to create plugin information from manifest for plugin 'mbtiles.jar'. Cause: org.openstreetmap.josm.plugins.PluginException: An error occurred in plugin mbtiles. Cause: java.io.IOException: invalid manifest format
org.openstreetmap.josm.plugins.PluginListParseException: Failed to create plugin information from manifest for plugin 'mbtiles.jar'
	at org.openstreetmap.josm.plugins.PluginListParser.createInfo(PluginListParser.java:44)
	at org.openstreetmap.josm.plugins.PluginListParser.addPluginInformation(PluginListParser.java:96)
	at org.openstreetmap.josm.plugins.PluginListParser.parse(PluginListParser.java:77)
	at org.openstreetmap.josm.plugins.ReadLocalPluginInformationTask.processLocalPluginInformationFile(ReadLocalPluginInformationTask.java:148)
	at org.openstreetmap.josm.plugins.ReadLocalPluginInformationTask.scanSiteCacheFiles(ReadLocalPluginInformationTask.java:96)
	at org.openstreetmap.josm.plugins.ReadLocalPluginInformationTask.scanLocalPluginRepository(ReadLocalPluginInformationTask.java:138)
	at org.openstreetmap.josm.plugins.ReadLocalPluginInformationTask.realRun(ReadLocalPluginInformationTask.java:188)
	at org.openstreetmap.josm.gui.PleaseWaitRunnable.doRealRun(PleaseWaitRunnable.java:93)
	at org.openstreetmap.josm.gui.PleaseWaitRunnable.run(PleaseWaitRunnable.java:141)
	at org.openstreetmap.josm.plugins.PluginHandler.loadLocallyAvailablePluginInformation(PluginHandler.java:824)
	at org.openstreetmap.josm.plugins.PluginHandler.buildListOfPluginsToLoad(PluginHandler.java:892)
	at org.openstreetmap.josm.gui.MainApplication.updateAndLoadEarlyPlugins(MainApplication.java:414)
	at org.openstreetmap.josm.gui.MainApplication.main(MainApplication.java:344)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.javaws.Launcher.executeApplication(Unknown Source)
	at com.sun.javaws.Launcher.executeMainClass(Unknown Source)
	at com.sun.javaws.Launcher.doLaunchApp(Unknown Source)
	at com.sun.javaws.Launcher.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.openstreetmap.josm.plugins.PluginException: An error occurred in plugin mbtiles
	at org.openstreetmap.josm.plugins.PluginInformation.<init>(PluginInformation.java:148)
	at org.openstreetmap.josm.plugins.PluginListParser.createInfo(PluginListParser.java:40)
	... 21 more
Caused by: java.io.IOException: invalid manifest format
	at java.util.jar.Manifest.read(Unknown Source)
	at org.openstreetmap.josm.plugins.PluginInformation.<init>(PluginInformation.java:142)
	... 22 more

````

````
URL:http://josm.openstreetmap.de/svn/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2017-03-14 19:27:54 +0100 (Tue, 14 Mar 2017)
Build-Date:2017-03-15 02:34:28
Revision:11732
Relative:URL: ^/trunk

Identification: JOSM/1.5 (11732 en) Windows 10 64-Bit
Memory Usage: 1555 MB / 3641 MB (896 MB allocated, but free)
Java version: 1.8.0_121-b13, Oracle Corporation, Java HotSpot(TM) 64-Bit Server VM
Screen: \Display0 1680x1050
Maximum Screen Size: 1680x1050
VM arguments: [-Djava.security.manager, -Djava.security.policy=file:<java.home>\lib\security\javaws.policy, -DtrustProxy=true, -Djnlpx.home=<java.home>\bin, -Djnlpx.origFilenameArg=C:\Program Files (x86)\josm-latest-mehr-RAM.jnlp, -Djnlpx.remove=false, -Djava.util.Arrays.useLegacyMergeSort=true, -Djnlpx.heapsize=1024m,4096m, -Djnlpx.splashport=51889, -Djnlpx.jvm=<java.home>\bin\javaw.exe]

````

**Comment by iandees** [comment]
Does JOSM read the manifest when I copy the .jar into the plugins directory directly? I can't reproduce this locally.

**Comment by iandees** [comment]
Ah, I downloaded the JAR from GitHub and see that the manifest is different from the one built locally.

From GitHub (as viewed in vim):

```
Manifest-Version: 1.0^M
Ant-Version: Apache Ant 1.8.2^M
Created-By: 1.8.0_111-b14 (Oracle Corporation)^M
Author: Ian Dees^M
Plugin-Class: org.openstreetmap.josm.plugins.mbtiles.MbtilesPlugin^M
Plugin-Date: 2017-03-14 20:51:47 -0700
^M
Plugin-Description: Allows you to view a local mbtiles database as a r^M
 aster layer.^M
Plugin-Icon: images/preferences/mbtiles.png^M
Plugin-Link: http://wiki.openstreetmap.org/index.php/JOSM/Plugins/Mbti^M
 les^M
Plugin-Mainversion: 10407^M
Plugin-Version: v2.2.0^M
^M
```

Built locally (as viewed in vim):

```
Manifest-Version: 1.0
Ant-Version: Apache Ant 1.10.1
Created-By: 1.8.0_102-b14 (Oracle Corporation)
Author: Ian Dees
Plugin-Class: org.openstreetmap.josm.plugins.mbtiles.MbtilesPlugin
Plugin-Date: 2017-03-14 20:51:47 -0700
Plugin-Description: Allows you to view a local mbtiles database as a r
 aster layer.
Plugin-Icon: images/preferences/mbtiles.png
Plugin-Link: http://wiki.openstreetmap.org/index.php/JOSM/Plugins/Mbti
 les
Plugin-Mainversion: 10407
Plugin-Version: v2.2.0

```

**Comment by iandees** [comment]
Looks like maybe there's an extra newline after `Plugin-Date`?

**Comment by iandees** [comment]
I rebuilt the jar locally and uploaded it to GitHub. It looks like Travis is using a 6 year old version of ant, and it generates an invalid manifest?

**Comment by iandees** [comment]
The version I built and posted seems to download and install correctly in JOSM 11639.
