### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by batje** [iandees/josm-mbtiles#6]
I downloaded the new version in Josm  8969 and I get the following error when starting

{{{
Repository Root: http://josm.openstreetmap.de/svn
Build-Date: 2015-10-30 02:32:24
Last Changed Author: Don-vip
Revision: 8969
Repository UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Relative URL: ^/trunk
URL: http://josm.openstreetmap.de/svn/trunk
Last Changed Date: 2015-10-29 22:15:23 +0100 (Thu, 29 Oct 2015)
Last Changed Rev: 8969

Identification: JOSM/1.5 (8969 en) Linux Ubuntu 14.04.3 LTS
Memory Usage: 348 MB / 1767 MB (282 MB allocated, but free)
Java version: 1.7.0_85, Oracle Corporation, OpenJDK 64-Bit Server VM
Java package: openjdk-7-jre:amd64-7u85-2.6.1-5ubuntu0.14.04.1

Plugins:
- ColorPlugin (1414145445)
- OSMRecPlugin (31772)
- alignways
- apache-commons (31772)
- buildings_tools
- ejml (31772)
- fieldpapers (v0.4.0)
- geotools (31772)
- jts (31772)
- log4j (31772)
- mbtiles
- pbf (31772)
- public_transport
- tageditor (31772)
- wikipedia

Last errors/warnings:
- E: java.lang.UnsupportedClassVersionError: org/openstreetmap/josm/plugins/mbtiles/MbtilesPlugin : Unsupported major.minor version 52.0

java.lang.UnsupportedClassVersionError: org/openstreetmap/josm/plugins/mbtiles/MbtilesPlugin : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:278)
	at org.openstreetmap.josm.plugins.PluginInformation.loadClass(PluginInformation.java:351)
	at org.openstreetmap.josm.plugins.PluginHandler.loadPlugin(PluginHandler.java:705)
	at org.openstreetmap.josm.plugins.PluginHandler.loadPlugins(PluginHandler.java:770)
	at org.openstreetmap.josm.plugins.PluginHandler.loadLatePlugins(PluginHandler.java:809)
	at org.openstreetmap.josm.gui.MainApplication.main(MainApplication.java:463)
}}}

**Comment by iandees** [comment]
Interesting. That's the same version of the JDK that I built with, which should have prevented this problem. I will try re-building it tonight.

**Comment by don-vip** [comment]
No, the jar has been built with JDK8, see MANIFEST.MF:

Manifest-Version: 1.0
Ant-Version: Apache Ant 1.9.6
Created-By: 1.8.0_60-b27 (Oracle Corporation)

**Comment by iandees** [comment]
That'd do it. Thanks @don-vip.

**Comment by drkludge** [comment]
I am familiar with the compile/run time mismatch.  I didn't notice the
problem last night because I am running Java 8.

**Comment by iandees** [comment]
I uploaded [a new revision](https://github.com/iandees/josm-mbtiles/releases/download/v2.0.1/mbtiles.jar) that was built to target 1.6 and above. Let me know how it works.

**Comment by don-vip** [comment]
Why 1.6? Josm requires java 7.

**Comment by batje** [comment]
The latest release solved the issue for me. Really great, deploying to 20 more people as we speak :-)

**Comment by iandees** [comment]
@don-vip: It was basically a typo that I decided wasn't important enough to change back.

Glad it worked for you, @batje!
